name: Test

on:
  push:
    branches:
      - master
      - develop
      - feature/carthage
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Run Unit Tests
        run: xcodebuild test -scheme ZincTests -workspace Zinc-ObjC.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14'
